### ISSUE TITLE
Documentation for integrating with Jenkins CI

### ISSUE THREAD

**Issue by pradgnyakulkarni** [mattn/goveralls#129]
Please show an example or documentation on how  to integrate goveralls with Jenkins

**Comment by pradgnyakulkarni** [comment]
Hi there is anyone looking in to this issue? Is there a way to use gocoveralls with Jenkins CI using API or any other way?

**Comment by mattn** [comment]
@mtenrer Could you please explain how to use goveralls with Jenkins?

**Comment by mtenrero** [comment]
@mattn of course. @pradgnyakulkarni It's quite simple After download all deps. make an step executing go tests with code coverage options:

```groovy
 stage('Test') {
            steps {
                sh 'cd $GOPATH/src/github.com/mtenrero/ATQ-Director && go test ./... -coverprofile=coverage.txt -covermode=atomic'
            }
}
```

And then , just simply call goveralls with your token and the reference of your coverprofile:
```groovy
stage('Code Coverage') {
            environment { 
                COVERTOKEN = credentials('coveralls-token') 
            }
            
            steps {
                sh 'cd $GOPATH/src/github.com/mtenrero/ATQ-Director && goveralls -coverprofile=coverage.txt -repotoken $COVERTOKEN'
            }
}
```

If you need a real-life Jenkinsfile example you can take a look to my repo: https://github.com/mtenrero/ATQ-Director/blob/master/Jenkinsfile It's also using **dep** as a package manager. 

The worst and the ugly part here is we need to go to the $GOPATH location for each command due to Jenkins workspace behaviour.

**Comment by gdm85** [comment]
I have opened a PR to address #179; there is a wide range of options on how to do this on Jenkins so I limited myself to a simple example.
