### ISSUE TITLE
Shallow Coveralls client errors

### ISSUE THREAD

**Issue by gkech** [mattn/goveralls#204]
Hello all,

Sometimes when coveralls is under maintenance, we have situations where you receive back client errors that could lead to issues with the CI pipelines - depending of course on how you configure them.

Is the possibility of creating a flag similar to that https://github.com/mattn/goveralls/blob/master/goveralls.go#L65 something we would like to explore? Or maybe make the already existing flag available for the client errors.

Thanks a lot

**Comment by shogo82148** [comment]
coveralls is still under maintenance...
https://status.coveralls.io/incidents/8zbjrwpb4frv
![image](https://user-images.githubusercontent.com/1157344/134082433-944b849f-1e36-4f20-8c53-e971e12d9fd4.png)
![image](https://user-images.githubusercontent.com/1157344/134083086-6644f983-4a0f-4ce9-8ace-5d7285ac154a.png)

Coveralls returns 405 Method Not Allowed.

https://github.com/shogo82148/actions-goveralls/runs/3656874218?check_suite_focus=true#step:7:111

```
bad response status from coveralls: 405
<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

The client errors should be reported because they mean that goveralls has some problem.
I want not to shallow these errors.

How about just shallowing the status code 405?

**Comment by gkech** [comment]
> coveralls is still under maintenance...
> https://status.coveralls.io/incidents/8zbjrwpb4frv
> ![image](https://user-images.githubusercontent.com/1157344/134082433-944b849f-1e36-4f20-8c53-e971e12d9fd4.png)
> ![image](https://user-images.githubusercontent.com/1157344/134083086-6644f983-4a0f-4ce9-8ace-5d7285ac154a.png)
> 
> Coveralls returns 405 Method Not Allowed.
> 
> https://github.com/shogo82148/actions-goveralls/runs/3656874218?check_suite_focus=true#step:7:111
> 
> ```
> bad response status from coveralls: 405
> <html>
> <head><title>405 Not Allowed</title></head>
> <body>
> <center><h1>405 Not Allowed</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> ```
> 
> The client errors should be reported because they mean that goveralls has some problem.
> I want not to shallow these errors.
> 
> How about just shallowing the status code 405?

sounds good! rocket fast implementation 🚀 ! thanks
